# Generated by Django 4.1.7 on 2023-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nomi', max_length=123)),
                ('lacation', models.CharField(help_text='davlatlar', max_length=255)),
                ('phone_number', models.CharField(help_text='Telefon raqami', max_length=100, unique=True)),
                ('checked', models.BooleanField(default=False, help_text='Tekshirilganmi?')),
                ('campany_name', models.CharField(help_text='Kampaniya nomi', max_length=123)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Sana')),
            ],
            options={
                'verbose_name': 'Sorvovlar mahsulot joylash',
                'verbose_name_plural': 'Sorvovlar mahsulot joylash',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nomi', max_length=123)),
                ('lacation', models.CharField(help_text='davlatlar', max_length=255)),
                ('phone_number', models.CharField(help_text='Telefon raqami', max_length=100, unique=True)),
                ('checked', models.BooleanField(default=False, help_text='Tekshirilganmi?')),
                ('text', models.TextField(help_text='Matn')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Sana')),
            ],
            options={
                'verbose_name': 'Savollar',
                'verbose_name_plural': 'Sorvovlar',
            },
        ),
    ]
