# Generated by Django 4.1.7 on 2023-08-21 20:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_application_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
